baseURL = 'https://alinco2020.github.io/AntHead/'
languageCode = 'ja-jp'
title = 'AntHead'
theme = 'anthead'
customCSS= ["/css/style.css"]

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = false
pygmentsstyle = "solarized-dark256"