baseURL = 'https://alinco2020.github.io/AntHead/'
languageCode = 'ja-jp'
title = 'AntHead'
theme = 'anthead'
customCSS= ["/css/style.css"]

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = false
pygmentsstyle = "solarized-dark256"
enableGitInfo = true
buildFuture = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[taxonomies]
    tag = "tags"
    lastmod = "lastmod"

[markup.goldmark.parser.attribute]
    block = true

[frontmatter]
    lastmod=":git"